const playerImages = {
    '이의리':'https://sports-phinf.pstatic.net/player/kbo/default/51648.png?type=w150', '데일':'https://sports-phinf.pstatic.net/player/kbo/default/56632.png?type=w150', '김호령':'https://sports-phinf.pstatic.net/player/kbo/default/65653.png?type=w150',
    '김선빈':'https://sports-phinf.pstatic.net/player/kbo/default/78603.png?type=w150', '김도영':'https://sports-phinf.pstatic.net/player/kbo/default/52605.png?type=w150', '카스트로':'https://sports-phinf.pstatic.net/player/kbo/default/56626.png?type=w150',
    '나성범':'https://sports-phinf.pstatic.net/player/kbo/default/62947.png?type=w150', '한준수':'https://sports-phinf.pstatic.net/player/kbo/default/68646.png?type=w150', '박상준':'https://sports-phinf.pstatic.net/player/kbo/default/52634.png?type=w150',
    '박재현':'https://sports-phinf.pstatic.net/player/kbo/default/55636.png?type=w150', '네일':'https://sports-phinf.pstatic.net/player/kbo/default/54640.png?type=w150', '김태형':'https://sports-phinf.pstatic.net/player/kbo/default/55610.png?type=w150',
    '양현종':'https://sports-phinf.pstatic.net/player/kbo/default/77637.png?type=w150', '김태군':'https://sports-phinf.pstatic.net/player/kbo/default/78122.png?type=w150', '올러':'https://sports-phinf.pstatic.net/player/kbo/default/55633.png?type=w150',
    '정현창':'https://sports-phinf.pstatic.net/player/kbo/default/55926.png?type=w150', '윤도현':'https://sports-phinf.pstatic.net/player/kbo/default/52667.png?type=w150', '박민':'https://sports-phinf.pstatic.net/player/kbo/default/50657.png?type=w150',
    '오선우':'https://sports-phinf.pstatic.net/player/kbo/default/69636.png?type=w150', '고종욱':'https://sports-phinf.pstatic.net/player/kbo/default/61353.png?type=w150', '이창진':'https://sports-phinf.pstatic.net/player/kbo/default/64560.png?type=w150',
    '후라도':'https://sports-phinf.pstatic.net/player/kbo/default/53375.png?type=w150', '원태인':'https://sports-phinf.pstatic.net/player/kbo/default/69446.png?type=w150', '최원태':'https://sports-phinf.pstatic.net/player/kbo/default/65320.png?type=w150',
    '양창섭':'https://sports-phinf.pstatic.net/player/kbo/default/68415.png?type=w150', '이승현':'https://sports-phinf.pstatic.net/player/kbo/default/51454.png?type=w150', '박승규':'https://sports-phinf.pstatic.net/player/kbo/default/69418.png?type=w150',
    '김지찬':'https://sports-phinf.pstatic.net/player/kbo/default/50458.png?type=w150', '김성윤':'https://sports-phinf.pstatic.net/player/kbo/default/67449.png?type=w150', '최형우':'https://sports-phinf.pstatic.net/player/kbo/default/72443.png?type=w150',
    '구자욱':'https://sports-phinf.pstatic.net/player/kbo/default/62404.png?type=w150', '디아즈':'https://sports-phinf.pstatic.net/player/kbo/default/54400.png?type=w150', '류지혁':'https://sports-phinf.pstatic.net/player/kbo/default/62234.png?type=w150',
    '강민호':'https://sports-phinf.pstatic.net/player/kbo/default/74540.png?type=w150', '박세혁':'https://sports-phinf.pstatic.net/player/kbo/default/62244.png?type=w150', '이재현':'https://sports-phinf.pstatic.net/player/kbo/default/52415.png?type=w150',
    '김영웅':'https://sports-phinf.pstatic.net/player/kbo/default/52430.png?type=w150', '김헌곤':'https://sports-phinf.pstatic.net/player/kbo/default/61404.png?type=w150', '함수호':'https://sports-phinf.pstatic.net/player/kbo/default/55440.png?type=w150',
    '전병우':'https://sports-phinf.pstatic.net/player/kbo/default/65586.png?type=w150', '양우현':'https://sports-phinf.pstatic.net/player/kbo/default/69403.png?type=w150', '김태훈':'https://sports-phinf.pstatic.net/player/kbo/default/65040.png?type=w150',
    '김재혁':'https://sports-phinf.pstatic.net/player/kbo/default/52424.png?type=w150', '베니지아노':'https://sports-phinf.pstatic.net/player/kbo/default/56841.png?type=w150', '박성한':'https://sports-phinf.pstatic.net/player/kbo/default/67893.png?type=w150',
    '정준재':'https://sports-phinf.pstatic.net/player/kbo/default/54812.png?type=w150', '최정':'https://sports-phinf.pstatic.net/player/kbo/default/75847.png?type=w150', '에레디아':'https://sports-phinf.pstatic.net/player/kbo/default/53827.png?type=w150',
    '한유섬':'https://sports-phinf.pstatic.net/player/kbo/default/62895.png?type=w150', '김성욱':'https://sports-phinf.pstatic.net/player/kbo/default/62934.png?type=w150', '최지훈':'https://sports-phinf.pstatic.net/player/kbo/default/50854.png?type=w150',
    '오태곤':'https://sports-phinf.pstatic.net/player/kbo/default/60558.png?type=w150', '이지영':'https://sports-phinf.pstatic.net/player/kbo/default/79456.png?type=w150', '이호연':'https://sports-phinf.pstatic.net/player/kbo/default/68504.png?type=w150',
    '오원석':'https://sports-phinf.pstatic.net/player/kbo/default/50859.png?type=w150', '최원준':'https://sports-phinf.pstatic.net/player/kbo/default/66606.png?type=w150', '김민혁':'https://sports-phinf.pstatic.net/player/kbo/default/64004.png?type=w150',
    '김현수':'https://sports-phinf.pstatic.net/player/kbo/default/76290.png?type=w150', '장성우':'https://sports-phinf.pstatic.net/player/kbo/default/78548.png?type=w150', '힐리어드':'https://sports-phinf.pstatic.net/player/kbo/default/56034.png?type=w150',
    '오윤석':'https://sports-phinf.pstatic.net/player/kbo/default/64504.png?type=w150', '김상수':'https://sports-phinf.pstatic.net/player/kbo/default/79402.png?type=w150', '배정대':'https://sports-phinf.pstatic.net/player/kbo/default/64166.png?type=w150', '이강민':'https://sports-phinf.pstatic.net/player/kbo/default/56006.png?type=w150',
    
    // 추가된 선수들
    '신민혁':'https://sports-phinf.pstatic.net/player/kbo/default/68902.png?type=w150',
    '김주원':'https://sports-phinf.pstatic.net/player/kbo/default/51907.png?type=w150',
    '박민우':'https://sports-phinf.pstatic.net/player/kbo/default/62907.png?type=w150',
    '박건우':'https://sports-phinf.pstatic.net/player/kbo/default/79215.png?type=w150',
    '데이비슨':'https://sports-phinf.pstatic.net/player/kbo/default/54944.png?type=w150',
    '이우성':'https://sports-phinf.pstatic.net/player/kbo/default/63260.png?type=w150',
    '도태훈':'https://sports-phinf.pstatic.net/player/kbo/default/66965.png?type=w150',
    '안중열':'https://sports-phinf.pstatic.net/player/kbo/default/64022.png?type=w150',
    '박시원':'https://sports-phinf.pstatic.net/player/kbo/default/50996.png?type=w150',
    '최정원':'https://sports-phinf.pstatic.net/player/kbo/default/69992.png?type=w150',
    '김규성':'https://sports-phinf.pstatic.net/player/kbo/default/66614.png?type=w150',
    '장찬희':'https://sports-phinf.pstatic.net/player/kbo/default/56460.png?type=w150',
    '곽빈':'https://sports-phinf.pstatic.net/player/kbo/default/68220.png?type=w150',
    '박찬호':'https://sports-phinf.pstatic.net/player/kbo/default/64646.png?type=w150',
    '카메론':'https://sports-phinf.pstatic.net/player/kbo/default/56251.png?type=w150',
    '박준순':'https://sports-phinf.pstatic.net/player/kbo/default/55252.png?type=w150',
    '양의지':'https://sports-phinf.pstatic.net/player/kbo/default/76232.png?type=w150',
    '양석환':'https://sports-phinf.pstatic.net/player/kbo/default/64153.png?type=w150',
    '김민석':'https://sports-phinf.pstatic.net/player/kbo/default/53554.png?type=w150',
    '강승호':'https://sports-phinf.pstatic.net/player/kbo/default/63123.png?type=w150',
    '임종성':'https://sports-phinf.pstatic.net/player/kbo/default/54236.png?type=w150',
    '정수빈':'https://sports-phinf.pstatic.net/player/kbo/default/79231.png?type=w150',
    '심재훈':'https://sports-phinf.pstatic.net/player/kbo/default/55438.png?type=w150',
    '주효상':'https://sports-phinf.pstatic.net/player/kbo/default/66354.png?type=w150',
    '오러클린':'https://sports-phinf.pstatic.net/player/kbo/default/56464.png?type=w150',
    '오석주':'https://sports-phinf.pstatic.net/player/kbo/default/67116.png?type=w150',
    '박준현':'https://sports-phinf.pstatic.net/player/kbo/default/56318.png?type=w150',
    '박주홍':'https://sports-phinf.pstatic.net/player/kbo/default/50357.png?type=w150',
    '최주환':'https://sports-phinf.pstatic.net/player/kbo/default/76267.png?type=w150',
    '안치홍':'https://sports-phinf.pstatic.net/player/kbo/default/79608.png?type=w150',
    '임병욱':'https://sports-phinf.pstatic.net/player/kbo/default/64346.png?type=w150',
    '브룩스':'https://sports-phinf.pstatic.net/player/kbo/default/56322.png?type=w150',
    '양현종 ':'https://sports-phinf.pstatic.net/player/kbo/default/55370.png?type=w150',
    '권혁빈':'https://sports-phinf.pstatic.net/player/kbo/default/55371.png?type=w150',
    '송지후':'https://sports-phinf.pstatic.net/player/kbo/default/54394.png?type=w150',
    '김재현':'https://sports-phinf.pstatic.net/player/kbo/default/62332.png?type=w150',
    '테일러':'https://sports-phinf.pstatic.net/player/kbo/default/56966.png?type=w150',
    '라일리':'https://sports-phinf.pstatic.net/player/kbo/default/55903.png?type=w150',
    '신영우':'https://sports-phinf.pstatic.net/player/kbo/default/53919.png?type=w150',
    '구창모':'https://sports-phinf.pstatic.net/player/kbo/default/65933.png?type=w150',
    '김휘집':'https://sports-phinf.pstatic.net/player/kbo/default/51344.png?type=w150',
    '서호철':'https://sports-phinf.pstatic.net/player/kbo/default/69995.png?type=w150',
    '김형준':'https://sports-phinf.pstatic.net/player/kbo/default/68912.png?type=w150',
    '토다':'https://sports-phinf.pstatic.net/player/kbo/default/56911.png?type=w150',
    '오영수':'https://sports-phinf.pstatic.net/player/kbo/default/68904.png?type=w150',
    '신재인':'https://sports-phinf.pstatic.net/player/kbo/default/56909.png?type=w150',
    '김정호':'https://sports-phinf.pstatic.net/player/kbo/default/51903.png?type=w150',
    '목지훈':'https://sports-phinf.pstatic.net/player/kbo/default/53973.png?type=w150',
    '한석현':'https://sports-phinf.pstatic.net/player/kbo/default/64101.png?type=w150',
    '김한별':'https://sports-phinf.pstatic.net/player/kbo/default/50902.png?type=w150',
    '황동하':'https://sports-phinf.pstatic.net/player/kbo/default/52641.png?type=w150',
    '나균안':'https://sports-phinf.pstatic.net/player/kbo/default/67539.png?type=w150',
    '한승연':'https://sports-phinf.pstatic.net/player/kbo/default/52628.png?type=w150',
    '비슬리':'https://sports-phinf.pstatic.net/player/kbo/default/56523.png?type=w150',
    '한태양':'https://sports-phinf.pstatic.net/player/kbo/default/52568.png?type=w150',
    '노진혁':'https://sports-phinf.pstatic.net/player/kbo/default/62931.png?type=w150',
    '레이예스':'https://sports-phinf.pstatic.net/player/kbo/default/54529.png?type=w150',
    '한동희':'https://sports-phinf.pstatic.net/player/kbo/default/68525.png?type=w150',
    '전준우':'https://sports-phinf.pstatic.net/player/kbo/default/78513.png?type=w150',
    '유강남':'https://sports-phinf.pstatic.net/player/kbo/default/61102.png?type=w150',
    '신윤후':'https://sports-phinf.pstatic.net/player/kbo/default/69508.png?type=w150',
    '손성빈':'https://sports-phinf.pstatic.net/player/kbo/default/51528.png?type=w150',
    '전민재':'https://sports-phinf.pstatic.net/player/kbo/default/68205.png?type=w150',
    '박세웅':'https://sports-phinf.pstatic.net/player/kbo/default/64021.png?type=w150',
    '장두성':'https://sports-phinf.pstatic.net/player/kbo/default/68507.png?type=w150',
    '박승욱':'https://sports-phinf.pstatic.net/player/kbo/default/62802.png?type=w150',
    '이호준':'https://sports-phinf.pstatic.net/player/kbo/default/54598.png?type=w150',
    '고승민':'https://sports-phinf.pstatic.net/player/kbo/default/69517.png?type=w150',
    '나승엽':'https://sports-phinf.pstatic.net/player/kbo/default/51551.png?type=w150',
    '장승현':'https://sports-phinf.pstatic.net/player/kbo/default/63202.png?type=w150',
    '임찬규':'https://sports-phinf.pstatic.net/player/kbo/default/61101.png?type=w150',
    '홍창기':'https://sports-phinf.pstatic.net/player/kbo/default/66108.png?type=w150',
    '구본혁':'https://sports-phinf.pstatic.net/player/kbo/default/69100.png?type=w150',
    '오스틴':'https://sports-phinf.pstatic.net/player/kbo/default/53123.png?type=w150',
    '천성호':'https://sports-phinf.pstatic.net/player/kbo/default/50054.png?type=w150',
    '송찬의':'https://sports-phinf.pstatic.net/player/kbo/default/68110.png?type=w150',
    '오지환':'https://sports-phinf.pstatic.net/player/kbo/default/79109.png?type=w150',
    '박해민':'https://sports-phinf.pstatic.net/player/kbo/default/62415.png?type=w150',
    '이재원':'https://sports-phinf.pstatic.net/player/kbo/default/68106.png?type=w150',
    '박동원':'https://sports-phinf.pstatic.net/player/kbo/default/79365.png?type=w150',
    '최승용':'https://sports-phinf.pstatic.net/player/kbo/default/51264.png?type=w150',
    '홍성호':'https://sports-phinf.pstatic.net/player/kbo/default/66233.png?type=w150',
    '박지훈':'https://sports-phinf.pstatic.net/player/kbo/default/50204.png?type=w150',
    '오명진':'https://sports-phinf.pstatic.net/player/kbo/default/50208.png?type=w150',
    '로드리게스':'https://sports-phinf.pstatic.net/player/kbo/default/56531.png?type=w150',
    '황성빈':'https://sports-phinf.pstatic.net/player/kbo/default/50500.png?type=w150',
    '윤동희':'https://sports-phinf.pstatic.net/player/kbo/default/52591.png?type=w150',
    '김재환':'https://sports-phinf.pstatic.net/player/kbo/default/78224.png?type=w150',
    '김건우':'https://sports-phinf.pstatic.net/player/kbo/default/51867.png?type=w150',
    '조형우':'https://sports-phinf.pstatic.net/player/kbo/default/51865.png?type=w150',
    '최준우':'https://sports-phinf.pstatic.net/player/kbo/default/68868.png?type=w150',
    '사우어':'https://sports-phinf.pstatic.net/player/kbo/default/56032.png?type=w150',
    '허경민':'https://sports-phinf.pstatic.net/player/kbo/default/79240.png?type=w150',
    '한승택':'https://sports-phinf.pstatic.net/player/kbo/default/63722.png?type=w150',
    '류현진':'https://sports-phinf.pstatic.net/player/kbo/default/76715.png?type=w150',
    '황영묵':'https://sports-phinf.pstatic.net/player/kbo/default/54795.png?type=w150',
    '페라자':'https://sports-phinf.pstatic.net/player/kbo/default/54730.png?type=w150',
    '문현빈':'https://sports-phinf.pstatic.net/player/kbo/default/53764.png?type=w150',
    '강백호':'https://sports-phinf.pstatic.net/player/kbo/default/68050.png?type=w150',
    '노시환':'https://sports-phinf.pstatic.net/player/kbo/default/69737.png?type=w150',
    '이진영':'https://sports-phinf.pstatic.net/player/kbo/default/66657.png?type=w150',
    '김태연':'https://sports-phinf.pstatic.net/player/kbo/default/66704.png?type=w150',
    '최재훈':'https://sports-phinf.pstatic.net/player/kbo/default/78288.png?type=w150',
    '심우준':'https://sports-phinf.pstatic.net/player/kbo/default/64006.png?type=w150',
    '배동현':'https://sports-phinf.pstatic.net/player/kbo/default/51761.png?type=w150',
    '서건창':'https://sports-phinf.pstatic.net/player/kbo/default/78168.png?type=w150',
    '김건희':'https://sports-phinf.pstatic.net/player/kbo/default/53312.png?type=w150',
    '톨허스트':'https://sports-phinf.pstatic.net/player/kbo/default/55130.png?type=w150',
    '박계범':'https://sports-phinf.pstatic.net/player/kbo/default/64468.png?type=w150',
    '최준호':'https://sports-phinf.pstatic.net/player/kbo/default/53259.png?type=w150'
};
