const playerImages = {
    '이의리':'https://sports-phinf.pstatic.net/player/kbo/default/51648.png?type=w150', '데일':'https://sports-phinf.pstatic.net/player/kbo/default/56632.png?type=w150', '김호령':'https://sports-phinf.pstatic.net/player/kbo/default/65653.png?type=w150',
    '김선빈':'https://sports-phinf.pstatic.net/player/kbo/default/78603.png?type=w150', '김도영':'https://sports-phinf.pstatic.net/player/kbo/default/52605.png?type=w150', '카스트로':'https://sports-phinf.pstatic.net/player/kbo/default/56626.png?type=w150',
    '나성범':'https://sports-phinf.pstatic.net/player/kbo/default/62947.png?type=w150', '한준수':'https://sports-phinf.pstatic.net/player/kbo/default/68646.png?type=w150', '박상준':'https://sports-phinf.pstatic.net/player/kbo/default/52634.png?type=w150',
    '박재현':'https://sports-phinf.pstatic.net/player/kbo/default/55636.png?type=w150', '네일':'https://sports-phinf.pstatic.net/player/kbo/default/54640.png?type=w150', '김태형':'https://sports-phinf.pstatic.net/player/kbo/default/55610.png?type=w150',
    '양현종':'https://sports-phinf.pstatic.net/player/kbo/default/77637.png?type=w150', '김태군':'https://sports-phinf.pstatic.net/player/kbo/default/78122.png?type=w150', '올러':'https://sports-phinf.pstatic.net/player/kbo/default/55633.png?type=w150',
    '정현창':'https://sports-phinf.pstatic.net/player/kbo/default/55926.png?type=w150', '윤도현':'https://sports-phinf.pstatic.net/player/kbo/default/52667.png?type=w150', '박민':'https://sports-phinf.pstatic.net/player/kbo/default/50657.png?type=w150',
    '오선우':'https://sports-phinf.pstatic.net/player/kbo/default/69636.png?type=w150', '고종욱':'https://sports-phinf.pstatic.net/player/kbo/default/61353.png?type=w150', '이창진':'https://sports-phinf.pstatic.net/player/kbo/default/64560.png?type=w150',
    '후라도':'https://sports-phinf.pstatic.net/player/kbo/default/53375.png?type=w150', '원태인':'https://sports-phinf.pstatic.net/player/kbo/default/69446.png?type=w150', '최원태':'https://sports-phinf.pstatic.net/player/kbo/default/65320.png?type=w150',
    '양창섭':'https://sports-phinf.pstatic.net/player/kbo/default/68415.png?type=w150', '이승현':'https://sports-phinf.pstatic.net/player/kbo/default/51454.png?type=w150', '박승규':'https://sports-phinf.pstatic.net/player/kbo/default/69418.png?type=w150',
    '김지찬':'https://sports-phinf.pstatic.net/player/kbo/default/50458.png?type=w150', '김성윤':'https://sports-phinf.pstatic.net/player/kbo/default/67449.png?type=w150', '최형우':'https://sports-phinf.pstatic.net/player/kbo/default/72443.png?type=w150',
    '구자욱':'https://sports-phinf.pstatic.net/player/kbo/default/62404.png?type=w150', '디아즈':'https://sports-phinf.pstatic.net/player/kbo/default/54400.png?type=w150', '류지혁':'https://sports-phinf.pstatic.net/player/kbo/default/62234.png?type=w150',
    '강민호':'https://sports-phinf.pstatic.net/player/kbo/default/74540.png?type=w150', '박세혁':'https://sports-phinf.pstatic.net/player/kbo/default/62244.png?type=w150', '이재현':'https://sports-phinf.pstatic.net/player/kbo/default/52415.png?type=w150',
    '김영웅':'https://sports-phinf.pstatic.net/player/kbo/default/52430.png?type=w150', '김헌곤':'https://sports-phinf.pstatic.net/player/kbo/default/61404.png?type=w150', '함수호':'https://sports-phinf.pstatic.net/player/kbo/default/55440.png?type=w150',
    '전병우':'https://sports-phinf.pstatic.net/player/kbo/default/65586.png?type=w150', '양우현':'https://sports-phinf.pstatic.net/player/kbo/default/69403.png?type=w150', '김태훈':'https://sports-phinf.pstatic.net/player/kbo/default/65040.png?type=w150',
    '김재혁':'https://sports-phinf.pstatic.net/player/kbo/default/52424.png?type=w150', '베니지아노':'https://sports-phinf.pstatic.net/player/kbo/default/56841.png?type=w150', '박성한':'https://sports-phinf.pstatic.net/player/kbo/default/67893.png?type=w150',
    '정준재':'https://sports-phinf.pstatic.net/player/kbo/default/54812.png?type=w150', '최정':'https://sports-phinf.pstatic.net/player/kbo/default/75847.png?type=w150', '에레디아':'https://sports-phinf.pstatic.net/player/kbo/default/53827.png?type=w150',
    '한유섬':'https://sports-phinf.pstatic.net/player/kbo/default/62895.png?type=w150', '김성욱':'https://sports-phinf.pstatic.net/player/kbo/default/62934.png?type=w150', '최지훈':'https://sports-phinf.pstatic.net/player/kbo/default/50854.png?type=w150',
    '오태곤':'https://sports-phinf.pstatic.net/player/kbo/default/60558.png?type=w150', '이지영':'https://sports-phinf.pstatic.net/player/kbo/default/79456.png?type=w150', '이호연':'https://sports-phinf.pstatic.net/player/kbo/default/68504.png?type=w150',
    '오원석':'https://sports-phinf.pstatic.net/player/kbo/default/50859.png?type=w150', '최원준':'https://sports-phinf.pstatic.net/player/kbo/default/66606.png?type=w150', '김민혁':'https://sports-phinf.pstatic.net/player/kbo/default/64004.png?type=w150',
    '김현수':'https://sports-phinf.pstatic.net/player/kbo/default/76290.png?type=w150', '장성우':'https://sports-phinf.pstatic.net/player/kbo/default/78548.png?type=w150', '힐리어드':'https://sports-phinf.pstatic.net/player/kbo/default/56034.png?type=w150',
    '오윤석':'https://sports-phinf.pstatic.net/player/kbo/default/64504.png?type=w150', '김상수':'https://sports-phinf.pstatic.net/player/kbo/default/79402.png?type=w150', '배정대':'https://sports-phinf.pstatic.net/player/kbo/default/64166.png?type=w150', '이강민':'https://sports-phinf.pstatic.net/player/kbo/default/56006.png?type=w150',
    
    // 추가된 선수들
    '신민혁':'https://sports-phinf.pstatic.net/player/kbo/default/68902.png?type=w150',
    '김주원':'https://sports-phinf.pstatic.net/player/kbo/default/51907.png?type=w150',
    '박민우':'https://sports-phinf.pstatic.net/player/kbo/default/62907.png?type=w150',
    '박건우':'https://sports-phinf.pstatic.net/player/kbo/default/79215.png?type=w150',
    '데이비슨':'https://sports-phinf.pstatic.net/player/kbo/default/54944.png?type=w150',
    '이우성':'https://sports-phinf.pstatic.net/player/kbo/default/63260.png?type=w150',
    '도태훈':'https://sports-phinf.pstatic.net/player/kbo/default/66965.png?type=w150',
    '안중열':'https://sports-phinf.pstatic.net/player/kbo/default/64022.png?type=w150',
    '박시원':'https://sports-phinf.pstatic.net/player/kbo/default/50996.png?type=w150',
    '최정원':'https://sports-phinf.pstatic.net/player/kbo/default/69992.png?type=w150',
    '김규성':'https://sports-phinf.pstatic.net/player/kbo/default/66614.png?type=w150',
    '장찬희':'https://sports-phinf.pstatic.net/player/kbo/default/56460.png?type=w150',
    '곽빈':'https://sports-phinf.pstatic.net/player/kbo/default/68220.png?type=w150',
    '박찬호':'https://sports-phinf.pstatic.net/player/kbo/default/64646.png?type=w150',
    '카메론':'https://sports-phinf.pstatic.net/player/kbo/default/56251.png?type=w150',
    '박준순':'https://sports-phinf.pstatic.net/player/kbo/default/55252.png?type=w150',
    '양의지':'https://sports-phinf.pstatic.net/player/kbo/default/76232.png?type=w150',
    '양석환':'https://sports-phinf.pstatic.net/player/kbo/default/64153.png?type=w150',
    '김민석':'https://sports-phinf.pstatic.net/player/kbo/default/53554.png?type=w150',
    '강승호':'https://sports-phinf.pstatic.net/player/kbo/default/63123.png?type=w150',
    '임종성':'https://sports-phinf.pstatic.net/player/kbo/default/54236.png?type=w150',
    '정수빈':'https://sports-phinf.pstatic.net/player/kbo/default/79231.png?type=w150',
    '심재훈':'https://sports-phinf.pstatic.net/player/kbo/default/55438.png?type=w150',
    '주효상':'https://sports-phinf.pstatic.net/player/kbo/default/66354.png?type=w150',
    '오러클린':'https://sports-phinf.pstatic.net/player/kbo/default/56464.png?type=w150',
    '오석주':'https://sports-phinf.pstatic.net/player/kbo/default/67116.png?type=w150'
};
